import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';

const id=window.__ENS_REPLAY_ID__;
const token=new URLSearchParams(location.search).get('token')||'';
const qs=token?`?token=${encodeURIComponent(token)}`:'';
const apiBase=(id && id!=='__REPLAY_ID__'?`/api/replay/${encodeURIComponent(id)}`:`/api/replays`);
const withQ=s=>apiBase+(qs?qs+'&'+s:'?'+s);
const fullUrl=apiBase+qs;
const state={data:null,tick:0,playing:false,speed:1,camera:'free',follow:null,selected:null,recording:false,recorder:null,recorded:[],meshes:new Map(),applied:[],deltaTick:-1,blockEvents:[]};
const $=s=>document.querySelector(s);
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x8ea9bf);
const camera=new THREE.PerspectiveCamera(70,1,.05,2000); camera.position.set(12,12,18);
const renderer=new THREE.WebGLRenderer({canvas:$('#scene'),antialias:true,preserveDrawingBuffer:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2));
const controls=new OrbitControls(camera,renderer.domElement); controls.enableDamping=true;
scene.add(new THREE.HemisphereLight(0xffffff,0x445566,2));
const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(30,60,20);scene.add(sun);
const world=new THREE.Group();scene.add(world);const actors=new Map();
const mats={};
const boxGeo=new THREE.BoxGeometry(1,1,1);
function mat(name){return mats[name] ||= new THREE.MeshStandardMaterial({color:new THREE.Color(hashColor(name))});}
function hashColor(s){let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))>>>0;return ((h&255)<<16)|(((h>>8)&255)<<8)|((h>>16)&255)|0x202020;}
function resize(){const r=$('#viewer').getBoundingClientRect();camera.aspect=r.width/r.height;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height,false)}addEventListener('resize',resize);resize();
function buildWorld(){world.clear();state.meshes.clear();state.applied=[];state.deltaTick=-1;const b=state.data.blocks;if(!b)return;for(const it of b.items){const [x,y,z,m]=it;const mesh=new THREE.Mesh(boxGeo,mat(m));mesh.position.set(x+0.5,y+0.5,z+0.5);world.add(mesh);state.meshes.set(x+','+y+','+z,mesh)}world.position.set(-b.center[0],-b.center[1],-b.center[2]);}
function actor(id){if(actors.has(id))return actors.get(id);const g=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(.6,1.2,.35),new THREE.MeshStandardMaterial({color:0x4fc3ff}));body.position.y=.9;const head=new THREE.Mesh(new THREE.BoxGeometry(.52,.52,.52),new THREE.MeshStandardMaterial({color:0xffd2b0}));head.position.y=1.75;g.add(body,head);scene.add(g);actors.set(id,g);return g;}
function hideUnused(seen){for(const [id,g] of actors)g.visible=seen.has(id)}
function frameAt(t){let best=null;for(const f of state.data.frames){if(f.t>t)break;if(f.players)best=f}return best}
function revertDeltas(){for(const d of state.applied){if(d.kind==='break'){d.mesh.visible=true}else{world.remove(d.mesh);if(d.orig)d.orig.visible=true}}state.applied=[]}
function applyDelta(f){const parts=(f.payload||'').split('|');if(parts.length<5)return;const x=+parts[1],y=+parts[2],z=+parts[3],m=parts[4];const c=(state.data.blocks||{}).center||[0,0,0];const key=(x-c[0])+','+(y-c[1])+','+(z-c[2]);if(f.event==='BLOCK_BREAK'){const mesh=state.meshes.get(key);if(mesh&&mesh.visible){mesh.visible=false;state.applied.push({kind:'break',mesh})}}else if(f.event==='BLOCK_PLACE'){const orig=state.meshes.get(key);if(orig)orig.visible=false;const mesh=new THREE.Mesh(boxGeo,mat(m));mesh.position.set((x-c[0])+0.5,(y-c[1])+0.5,(z-c[2])+0.5);world.add(mesh);state.applied.push({kind:'place',mesh,orig:orig||null})}}
function applyDeltas(upto){if(upto<state.deltaTick)revertDeltas();for(const f of state.blockEvents){if(f.t<=state.deltaTick||f.t>upto)continue;applyDelta(f)}state.deltaTick=upto}
function killcam(){const box=$('#killcam');if(!box||!box.checked||!state.data)return;let best=null;for(const f of state.data.frames){if(f.t>state.tick)break;if(f.event==='ELIMINATION'&&state.tick-f.t<60)best=f}if(best){const killer=(best.payload||'').split('|')[1];if(killer&&killer!=='null'&&killer!=='undefined'&&killer!==''){state.camera='follow';state.follow=killer}}}
function renderTick(){applyDeltas(state.tick);const f=frameAt(state.tick);const seen=new Set();if(f?.players)for(const p of f.players){seen.add(p.id);const g=actor(p.id);g.visible=true;g.position.set(p.x,p.y,p.z);g.rotation.y=THREE.MathUtils.degToRad(-p.yaw);if(state.selected===p.id)g.scale.setScalar(1.15)}hideUnused(seen);if(state.camera==='follow'&&state.follow){const p=f?.players?.find(x=>x.id===state.follow);if(p){const target=new THREE.Vector3(p.x,p.y+1.3,p.z);camera.position.lerp(target.clone().add(new THREE.Vector3(4,2,6)),.12);controls.target.lerp(target,.12)}}if(state.camera==='first'&&state.follow){const p=f?.players?.find(x=>x.id===state.follow);if(p){camera.position.set(p.x,p.y+1.62,p.z);camera.rotation.set(THREE.MathUtils.degToRad(-p.pitch),THREE.MathUtils.degToRad(-p.yaw),0,'YXZ');controls.enabled=false}}else controls.enabled=true;updateInspector(f);}
function updateInspector(f){const p=f?.players?.find(x=>x.id===state.selected);if(!p){$('#inspector').textContent='Click a player in the list.';return}$('#inspector').innerHTML=`<div class="stat"><b>Health</b><span>${p.hp.toFixed(1)}</span><b>Food</b><span>${p.food}</span><b>Mode</b><span>${p.gm}</span><b>Position</b><span>${p.x.toFixed(2)}, ${p.y.toFixed(2)}, ${p.z.toFixed(2)}</span><b>Yaw/Pitch</b><span>${p.yaw.toFixed(1)} / ${p.pitch.toFixed(1)}</span></div><div class="inv">${(p.inv||[]).map(i=>`<div class="slot">${i.mat}<br>x${i.amount}</div>`).join('')}</div>`}
function playersUI(){const map=new Map(state.data.players.map(p=>[p.uuid,p]));$('#players').innerHTML=[...map].map(([u,p])=>`<div class="player" data-id="${u}"><span class="dot"></span><span>${p.name}</span></div>`).join('');document.querySelectorAll('.player').forEach(e=>e.onclick=()=>{state.selected=e.dataset.id;state.follow=e.dataset.id;document.querySelectorAll('.player').forEach(x=>x.classList.remove('active'));e.classList.add('active');renderTick()})}
function meta(){const d=state.data;$('#meta').innerHTML=`<div class="stat"><b>Arena</b><span>${d.arena}</span><b>Ticks</b><span>${d.durationTicks}</span><b>Players</b><span>${d.players.length}</span></div>`;$('#timeline').max=d.durationTicks||1;$('#status').textContent=`${d.arena} • ${d.players.length} players${d.partial?' • partial':''}`}
function eventsUI(){const ev=state.data.frames.filter(f=>f.event);$('#events').innerHTML=ev.map(e=>`<span class="event" title="${e.event}" style="flex:${Math.max(1,100/(state.data.durationTicks||1)*e.t)}" data-t="${e.t}"></span>`).join('');document.querySelectorAll('.event').forEach(x=>x.onclick=()=>{state.tick=+x.dataset.t;sync()})}
function sync(){state.tick=Math.max(0,Math.min(state.data.durationTicks,state.tick));$('#timeline').value=state.tick;$('#time').textContent=`${state.tick} / ${state.data.durationTicks}`;killcam();renderTick()}
async function load(){try{const s=await (await fetch(withQ('summary=1'))).json();if(s.error)throw Error(s.error||'Replay unavailable');const total=s.durationTicks||0;if(total>36000){$('#loading').textContent='Loading replay… (0%)';const half=Math.ceil(total/2);const a=await (await fetch(withQ(`from=0&to=${half}`))).json();$('#loading').textContent='Loading replay… (50%)';const b=await (await fetch(withQ(`from=${half+1}&to=${total}`))).json();state.data={...a,frames:[...(a.frames||[]),...(b.frames||[])]};}else{state.data=await (await fetch(fullUrl)).json();if(state.data.error)throw Error(state.data.error)}state.blockEvents=(state.data.frames||[]).filter(f=>f.event==='BLOCK_BREAK'||f.event==='BLOCK_PLACE');buildWorld();playersUI();meta();eventsUI();$('#loading').style.display='none';sync()}catch(e){$('#loading').textContent=e.message}}
$('#play').onclick=()=>{state.playing=!state.playing;$('#play').textContent=state.playing?'❚❚':'▶'};
$('#back').onclick=()=>{state.tick--;sync()};$('#forward').onclick=()=>{state.tick++;sync()};$('#timeline').oninput=e=>{state.tick=+e.target.value;sync()};$('#speed').onchange=e=>state.speed=parseFloat(e.target.value);
document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>{state.camera=b.dataset.camera;if(state.camera==='top'){camera.position.set(0,80,0);controls.target.set(0,0,0)};if(state.camera==='free')camera.position.set(12,12,18);});
$('#shot').onclick=()=>{const a=document.createElement('a');a.download=`${id}-${state.tick}.png`;a.href=renderer.domElement.toDataURL('image/png');a.click()};
$('#clip').onclick=()=>{if(!state.recording){const stream=renderer.domElement.captureStream(60);state.recorder=new MediaRecorder(stream,{mimeType:'video/webm'});state.recorded=[];state.recorder.ondataavailable=e=>e.data.size&&state.recorded.push(e.data);state.recorder.onstop=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(state.recorded,{type:'video/webm'}));a.download=`${id}-clip-${state.tick}.webm`;a.click()};state.recorder.start();state.recording=true;$('#clip').textContent='Stop Clip'}else{state.recorder.stop();state.recording=false;$('#clip').textContent='Record Clip'}};
function loop(){requestAnimationFrame(loop);if(state.playing){state.tick+=state.speed/2;if(state.tick>=state.data.durationTicks){state.tick=state.data.durationTicks;state.playing=false;$('#play').textContent='▶'}sync()}controls.update();renderer.render(scene,camera)}
load();loop();
